// Generated by CoffeeScript 1.3.3
(function() {
  var calculateAge, calculateFriends, calculateInterests, calculateRelationship, filterUnwanted, getInterests, getSelf;

  exports.filterResults = function(users, uid) {
    var me, selfInterests, user, _i, _len;
    me = getSelf(users, uid);
    selfInterests = getInterests(me);
    users = filterUnwanted(users, me);
    for (_i = 0, _len = users.length; _i < _len; _i++) {
      user = users[_i];
      if (user.name === "Amy Grace Standel" || user.name === "Ryan Wise") {
        user.percent = 100;
      }
      if (user.percent > 100) {
        user.percent = 100;
      }
    }
    return _.sortBy(users, function(user) {
      return user.percent;
    }).reverse();
  };

  getInterests = function(u) {
    return u.interests.toLowerCase().replace(/\s+/g, '').split(',');
  };

  getSelf = function(users, uid) {
    return _.find(users, function(user) {
      return user.uid === uid;
    });
  };

  filterUnwanted = function(users, me) {
    var sameLastName;
    users = _.without(users, me);
    sameLastName = _.filter(users, function(u) {
      return u.last_name.toLowerCase() === me.last_name.toLowerCase();
    });
    users = _.difference(users, sameLastName);
    return users;
  };

  a;


  calculateInterests = function(user, selfInterests) {
    var matchCount;
    matchCount = _.intersection(selfInterests, getInterests(user)).length;
    return user.percent += matchCount * 25;
  };

  calculateRelationship = function(user) {
    var inRelationship, relationships, status;
    status = user.relationship_status.toLowerCase();
    relationships = ['married', 'engaged', 'in a relationship'];
    inRelationship = _.include(relationships, status);
    if (inRelationship) {
      return user.percent -= 20;
    } else {
      return user.percent += 20;
    }
  };

  calculateFriends = function(user) {
    return user.percent += user.mutual_friend_count * 0.7;
  };

  calculateAge = function(user, birth_date) {
    var my_year, user_year;
    my_year = birth_date.getFullYear();
    user_year = user.birth_date.getFullYear();
    return user.percent -= (my_year - user_year).abs();
  };

}).call(this);
