// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, filterResults, http, path, routes;

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  app = express();

  app.configure = function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(require('connect-assets')());
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser('your secret here'));
    app.use(express.session());
    app.use(app.router);
    app.use(require('stylus').middleware(__dirname + '/public'));
    return app.use(express["static"](path.join(__dirname, 'public')));
  };

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', routes.index);

  app.post("/", function(req, res) {
    var users;
    users = filterResults(req.body);
    return res.send(filterResults(users));
  });

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port ${ app.get('port') ");
  });

  filterResults = function(users) {
    var percent, user, _i, _len, _ref;
    _ref = users.data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      user = _ref[_i];
      percent = Math.floor(Math.random() * 101);
      user.percent = percent;
    }
    return users;
  };

}).call(this);
