// Generated by CoffeeScript 1.3.3
(function() {
  var cluster;

  cluster = require('cluster');

  if (cluster.isMaster) {
    require('os').cpus().forEach(function() {
      return cluster.fork();
    });
    cluster.on('death', function(worker) {
      console.log('worker' + worker.pid + ' died');
      return cluster.fork();
    });
  } else {
    require('./app.js');
  }

}).call(this);
