// Generated by CoffeeScript 1.3.3
(function() {

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Matcher'
    });
  };

  exports.query = function(req, res) {
    return res.send(req.body);
  };

}).call(this);
